<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alba_am3969x1</name>
   <tag></tag>
   <elementGuidId>cc7cd5d5-477a-4757-9a04-e22b3a4d52a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/div/div[1]/div[2]/div[3]/div[1]/div/a/div/div/div[1]/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div[2]/div/div[1]/div[2]/div[3]/div[1]/div/a/div/div/div[1]/div/picture/img</value>
      <webElementGuid>8cfe8d7e-0a47-4ee5-811b-f29fd5d6b68d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
