<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lanjutkan</name>
   <tag></tag>
   <elementGuidId>2e01f550-aaa7-4b0b-9a7f-1f5296183228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/div/div/section/div/div/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div[2]/div/div/section/div/div/div[3]/div/button</value>
      <webElementGuid>b0d6fc12-fa82-476f-ae93-fe9b9db30a7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
