<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_simpan</name>
   <tag></tag>
   <elementGuidId>4a208a4b-c564-4892-a9a5-6deabb886011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[6]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[6]/button</value>
      <webElementGuid>7b026914-89d1-4694-a8a3-c5d3e79c3ca5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
