<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x</name>
   <tag></tag>
   <elementGuidId>1f14b8a8-2deb-419f-8be5-d79640269cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a9b09b3-1f78-4472-8232-bd60ce41c7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>c999e74b-47a8-492c-af2d-48446dcf0531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6ddfe79-cc94-4a5b-9bec-f5cc7dd03d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close close-icon moe-inapp-close moe-element</value>
      <webElementGuid>8898c6af-baaf-426e-bd07-8842ef0e5f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>ff4d7f27-b79d-4bdc-aab4-10df1513c73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>1b83f914-76c7-44e5-89a6-a55ffe7032b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x </value>
      <webElementGuid>00e29f39-4732-41fb-831d-891afb54c4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-icon&quot;)</value>
      <webElementGuid>3df0a7bc-49d6-4e60-8ac9-c454aed46302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Home/iframemoe-onsite-campaign-65b12d6dd987b5eb7a3e410c</value>
      <webElementGuid>bd9af47a-046b-445c-a20b-8bebb7f799a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-icon']</value>
      <webElementGuid>ca9166b0-7c36-43cd-86c5-19265623de79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>85566211-5351-4041-92f8-61d7026fd83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-icon' and (text() = ' x ' or . = ' x ')]</value>
      <webElementGuid>314f7cc6-a8ad-4d4f-9ad7-b6e7c3cb69ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
