<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x (1)</name>
   <tag></tag>
   <elementGuidId>91d472a1-98ba-4992-8c5c-ec23180cb677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3277bf45-afb7-4400-af2a-97487ff9ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>b4873ec8-be3a-4f4a-9914-d5614479143e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9bd4a2e-70db-4467-bc2a-530a90540a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close close-icon moe-inapp-close moe-element</value>
      <webElementGuid>56e3663c-ced1-40f4-8496-8c381a368257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>262405d2-7bbf-4174-a4f0-056fa4fdeea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>621f4dde-d6a6-44c5-8047-ca45040924c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x </value>
      <webElementGuid>c3db5662-81e0-48f1-9550-e2f0d8dd9b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-icon&quot;)</value>
      <webElementGuid>d886a319-0aca-4a37-a172-00ef702cfc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Home/iframemoe-onsite-campaign-65a64dd79dc8c68bc5b664f4</value>
      <webElementGuid>535770f4-cf9b-49dd-908b-e075705e4735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-icon']</value>
      <webElementGuid>d9ef4aca-6153-4681-85e0-381ad6ddb557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>358a750d-0b13-45ea-a0b1-fa3b1cf7f8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-icon' and (text() = ' x ' or . = ' x ')]</value>
      <webElementGuid>1d12747c-94b3-4b71-8a03-3867bfc157ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
