<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_isialamat</name>
   <tag></tag>
   <elementGuidId>60859e1e-aef2-4aed-8e01-ecd095596b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div[4]/button[2]</value>
      <webElementGuid>766aa820-c525-450f-921b-097c2fe7bf98</webElementGuid>
   </webElementProperties>
</WebElementEntity>
