<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti Saja</name>
   <tag></tag>
   <elementGuidId>de3e663f-e208-4db2-aa00-9c66adab439b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='moeRemoveBanner()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70b49762-6f2d-45d8-8008-291dd8383a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>moeRemoveBanner()</value>
      <webElementGuid>d14ed838-e71f-4ac4-8850-ccd43030feab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>d9fb6415-54cb-41b4-a05a-5dc26af9c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>c54fd799-2be1-4be1-9260-f3e3a842cad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti Saja</value>
      <webElementGuid>1fdec51e-fe95-4392-bb1a-36868a52ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopBannerWrapped&quot;)/div[1]/div[3]/div[2]/button[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>31c00f1e-b5cd-4d33-b749-c7c7a391ba39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='moeRemoveBanner()']</value>
      <webElementGuid>91f6977f-f4f6-4702-a573-27725f5cdc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div[2]/button</value>
      <webElementGuid>5fa0d289-0aff-4c0a-b7b3-eddfef86c8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d4ce24f2-4300-495a-aee9-8a3e427e4834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nanti Saja' or . = 'Nanti Saja')]</value>
      <webElementGuid>aa908b95-d9e1-456d-a441-588a26a69981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
