<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_search</name>
   <tag></tag>
   <elementGuidId>bb5f05f5-0143-4342-8d6e-947d24fd4fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div[1]/div[2]/div/div[2]/form/fieldset/div[1]/div[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div[1]/div[2]/div/div[2]/form/fieldset/div[1]/div[2]/div/button[2]</value>
      <webElementGuid>a54e17e4-44ed-4b4f-92ca-752909e58eea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
