<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_search</name>
   <tag></tag>
   <elementGuidId>7d2316c7-cbbf-4fdc-9210-0b3762d7971c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div[1]/div[2]/div/div[2]/form/fieldset/div[1]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div[1]/div[2]/div/div[2]/form/fieldset/div[1]/div[1]/input</value>
      <webElementGuid>e0ffde05-f552-44ac-8683-7a8234d7487c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
