<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_kpos</name>
   <tag></tag>
   <elementGuidId>267c2850-04b7-4e9e-8040-5e0f91d849e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[3]/div[2]/fieldset/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[3]/div[2]/fieldset/div[1]/div/input</value>
      <webElementGuid>aa51e2a6-7c64-4ccc-a3d1-775e097c6f04</webElementGuid>
   </webElementProperties>
</WebElementEntity>
