<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_alamat</name>
   <tag></tag>
   <elementGuidId>23a0e035-2f9d-4e02-a047-37ad33aa7b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[4]/fieldset/div[1]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-root&quot;]/div/div/div/div/div/div/div/div/form/div[4]/fieldset/div[1]/div/textarea</value>
      <webElementGuid>0db046c7-eadd-4deb-8d68-cd70c3280400</webElementGuid>
   </webElementProperties>
</WebElementEntity>
