<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>b18823e9-8a8a-436a-a9ed-d7fe32340f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3c48bae-bd65-41c2-a1cb-e5046700aee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>27b50de9-129a-4589-8002-ca2929bd03f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2</value>
      <webElementGuid>2327b94c-7f13-40a6-baf6-a2ef7a911829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-md bg-neutral-900&quot;]/div[@class=&quot;login-form-container&quot;]/div[@class=&quot;mx-auto my-0 text-neutral-200 login-form-popup p-3&quot;]/form[1]/div[@class=&quot;mb-5&quot;]/fieldset[@class=&quot;text-input border-none relative p-0 mb-2 qa-email-phone-field&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 pl-4 pr-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>c5053b6f-686e-4d19-88b5-6a8587d32d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>68fa01dc-a3a3-4493-bd82-2756c9b43b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>8013cd3a-6437-4a84-bb47-09276cc47441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/fieldset/div/div/input</value>
      <webElementGuid>7989a29c-4ece-431d-9502-9e5c78368b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>f1eb351b-8422-4542-a7a2-dc44fe4964ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
