<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>oke_map</name>
   <tag></tag>
   <elementGuidId>e197da1e-db34-4428-9cf0-b6a07c32ed24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-root&quot;]/div[2]/div/div/div/div/div/div/div[2]/div/div[1]/div[3]/div[1]/div[2]/div/div[3]/div[1]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-root&quot;]/div[2]/div/div/div/div/div/div/div[2]/div/div[1]/div[3]/div[1]/div[2]/div/div[3]/div[1]/div/button</value>
      <webElementGuid>522ccbf6-5ded-4538-9b57-cdc5c451fdd0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
