<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total_harga</name>
   <tag></tag>
   <elementGuidId>4609e082-8f7d-4412-a64e-90e5b6c720fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/main/section[2]/div[2]/div[3]/div/div[1]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div[2]/main/section[2]/div[2]/div[3]/div/div[1]/div[2]/div</value>
      <webElementGuid>9f23857b-af09-4dae-8fa0-46533e43f415</webElementGuid>
   </webElementProperties>
</WebElementEntity>
